name: Ping URL
description: Ping URL until max attempts have been exceeded. If resp is not 200 then fail. 

inputs:
  target_url: # INPUT_TARGET_URL
    description: URL to target with a series of pings. 
    required: true
  max_attempts: # INPUT_MAX_ATTEMPTS
    description: Maxiumu number of attempts until the action fails. 
    default: '10'
    required: false
  delay: # INPUT_DELAY
    description: Delay in seconds between attempts. 
    default: '5'
    required: false

outputs:
  url-reachable:
    description: Is the website up?
  
runs: 
  using: docker
  image: Dockerfile # this can also use docker hub or container registry. Kali box could be a lt of fun! 
  