name: Dependabot Alerts to Slack

on:
  schedule:
    - cron: '0 3 * * 0'  # Runs every Sunday at 3:00 AM UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  send-alerts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Dependabot alerts
        id: dependabot
        run: |
          # Fetch Dependabot alerts
          dependabot_alerts=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/vulnerability-alerts")

          # Print the raw response for debugging
          echo "$dependabot_alerts" | jq .

          # Check if alerts are present and process them
          if [ "$(echo "$dependabot_alerts" | jq '. | length')" -gt 0 ]; then
            echo "$dependabot_alerts" | jq -r '.[] | "\(.package.name) - \(.severity)"' > alerts.txt
            echo "::set-output name=alerts::$(cat alerts.txt)"
          else
            echo "No Dependabot alerts found."
            echo "::set-output name=alerts::No alerts"
          fi
        shell: /usr/bin/bash -e {0}

      - name: Send alerts to Slack
        if: steps.dependabot.outputs.alerts != 'No alerts'
        uses: slackapi/slack-github-action@v1
        with:
          slack-message: |
            Dependabot Alerts:
            $(cat alerts.txt)
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}