name: Dependabot Slack Notification
on:
  schedule:
    - cron: '0 3 * * 0'  # Runs at 3:00 AM every Sunday
  workflow_dispatch:  # Allows manual triggering
permissions:
  actions: write
  security-events: read
  
jobs:
  check-dependabot-alerts:
    runs-on: ubuntu-latest
    steps:
      - name: Check for Dependabot Alerts
        id: check-alerts
        env:
          GH_TOKEN: ${{ secrets.DEP_BOT_PAT }}
        run: |
          echo "Raw API response:"
          gh api repos/${{ github.repository }}/dependabot/alerts
          
          alerts=$(gh api repos/${{ github.repository }}/dependabot/alerts | jq -c '[.[] | {name: .security_advisory.summary, severity: .security_advisory.severity}]')
          echo "Processed alerts:"
          echo "$alerts"
          
          echo "ALERTS=$alerts" >> $GITHUB_ENV
          alert_count=$(echo $alerts | jq 'length')
          echo "ALERT_COUNT=$alert_count" >> $GITHUB_ENV
          if [ $alert_count -gt 0 ]; then
            echo "HAS_ALERTS=true" >> $GITHUB_ENV
          else
            echo "HAS_ALERTS=false" >> $GITHUB_ENV
          fi
      - name: Send Slack Notification
        if: env.HAS_ALERTS == 'true'
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: repo,message
          custom_payload: |
            cat << EOF
            {
              "text": ":warning: Dependabot Alert Notification",
              "attachments": [
                {
                  "color": "danger",
                  "fields": [
                    {
                      "title": "Repository",
                      "value": "${{ github.repository }}",
                      "short": true
                    },
                    {
                      "title": "Number of Alerts",
                      "value": "${{ env.ALERT_COUNT }}",
                      "short": true
                    },
                    {
                      "title": "Alerts",
                      "value": $(echo '${{ env.ALERTS }}' | jq -c '.'),
                      "short": false
                    }
                  ]
                }
              ]
            }
            EOF
        env:
          GITHUB_TOKEN: ${{ secrets.DEP_BOT_PAT }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}