name: 01 - Building Blocks
on: 
  workflow_dispatch: # this makes is so the job can only be triggered in the UI. 

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello World!"

  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Success step
        run: |
          echo "I will not fail now because of the exit 0 below."
          exit 0
      - name: Say Goodbye
        run: echo "Goodbye!"
