name: 15 - Working with Matrices
on:
    workflow_dispatch:

jobs:
    backwards-compatibility:
        name: ${{ matrix.os }}-${{ matrix.node-version }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false # If set to true then any failing job will cancel the others. Default is true
            matrix:
                node-version: [20.x, 21.x, 22.x]
                os:
                    - ubuntu-latest
                    #- macos-latest # commented out as this is expensive in a priv repo. 
                    - windows-latest
                include: # this allows you to extende the configuraiton. 
                   - os: ubuntu-latest # this will adds a new job only for ubuntu and not windows.
                     node-version: 21.x
                     tag: experimental 
        steps:
            - name: Setup Node
              uses: actions/setup-node@v3
              with: 
                node-version: ${{ matrix.node-version}}
            - name: Fail if experimental
              if: matrix.tag == 'experimental'
              run: exit 1
            - name: Run Tests
              run: | 
                echo "Running tests on OS ${{ matrix.os }} and NodeJS ${{ matrix.node-version }}"
                sleep 5
            - name: Upload test results
              run: |
                echo "Uploading test results"

    include-example: # this job goes into include: a bit more
        name: ${{ matrix.color }}-${{ matrix.shape }}-${{ matrix.size }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                color: [red, green]
                shape: [circle, square]
                size: [small, large]
                include: 
                - color: red
                  shape: triangle
        steps:
        - name: Dummy step
          run: echo "${{ matrix.color }}-${{ matrix.shape }}-${{ matrix.size }}"

      
    
                