name: 16 - Working with Environments
run-name: 16 - Working with Environments | env - ${{ inputs.target-env }}
on:
    workflow_dispatch:

jobs:
    echo-staging:
        runs-on: ubuntu-latest
        environment: staging
        env: 
            my-env-value: ${{ vars.MY_ENV_VALUE || 'default value' }}
        steps:
            - name: Echo Vars
              run: |
                echo "Env variables: ${{ env.my-env-value}}"
    e2e-tests:
        runs-on: ubuntu-latest
        needs: echo-staging
        steps:
            - name: E2E Tests
              run: echo "Running E2E tests"
    echo-prod:
        runs-on: ubuntu-latest
        needs: e2e-tests
        environment: prod
        env: 
            my-env-value: ${{ vars.MY_ENV_VALUE || 'default value' }}
        steps:
            - name: Echo Vars
              run: |
                echo "Env variables: ${{ env.my-env-value}}"
