name: 17 - Custom Actions - Composite
on:
    workflow_dispatch:

env: 
    working-directory: 17-custom-actions/react-app 

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: ${{ env.working-directory }}
    steps:
        - uses: actions/checkout@v4 # when using a custom action in the same repo you need to check it out
        - name: Setup Node and NPM Deps
          uses: ./.github/actions/composite-cache-deps # make use of the action created earlier
          with:
            node-version: 20.x # need to pass this into the custom action
            working-dir: ${{ env.working-directory }} # this is the dir where the package.lock file lives
        - name: Test
          run: npm run test
        - name: Build
          run: npm run build 
          