name: 17 - 2 - Custom Actions - JS
run-name: 17 - 2 - Custom Actions - JS | Base Branch ${{ inputs.base-branch }} Target Branch ${{ inputs.target-branch }} Working Dir ${{ inputs.working-directory}}
on:
    workflow_dispatch:
      inputs:
        base-branch:
          type: string
          default: main
        target-branch:
          type: string
          default: update-dependencies
        working-directory:
          type: string
          default: 17-custom-actions/react-app

permissions: # set permissions for the GITHUB_TOKEN used in the workflow
  contents: write
  pull-requests: write 

jobs:
  dep-update:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4 # when using a custom action in the same repo you need to check it out
        - name: Check for dependency updates
          uses: ./.github/actions/js-deps-update
          with:
            base-branch: ${{ inputs.base-branch }}
            target-branch: ${{ inputs.target-branch }}
            working-directory: ${{ inputs.working-directory }}
            gh-token: ${{ secrets.GITHUB_TOKEN }}
          