name: 17 - 3 - Custom Actions - Docker
on:
    workflow_dispatch:
      inputs:
        target-url:
          type: string
          default: http://www.google.com
        
jobs:
    ping-url:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Ping target URL
              uses: ./.github/actions/docker-ping-url
              with:
                url: ${{ inputs.target-url}}
